name: 'gdrive-delete-action'
description: 'GitHub Action that deletes a file or folder from Google Drive.'
author: 'Bonitasoft'

inputs:
  credentials:
    description: 'Google API credentials in base64 format.'
    required: true
  parent-folder-id:
    description: 'The parent folder ID in Google Drive.'
    required: true
  target-filepath:
    required: true
    description:
      'The remote file path in Google Drive of the file to delete relative to the
      given parent folder.'
  ignore-missing:
    description: 'Ignore error if the target file does not exist.'
    default: 'false'
  hard-delete:
    description: 'Permanently delete the file instead of moving it to the trash.'
    default: 'false'

outputs:
  file-id:
    description: 'The ID of the deleted file.'

runs:
  using: node20
  main: dist/index.js
